import type { CardDef } from "../types.js";

// NOTE: All card data authored from publicly known Seven Wonders base-game rules.
// minPlayers indicates the minimum player count at which this card copy enters the deck.

export const ALL_CARDS: readonly CardDef[] = [
  // ─── AGE I ─── BROWN (raw resources) ───
  {
    id: "lumber_yard_3p",
    name: "Lumber Yard",
    age: 1,
    minPlayers: 3,
    colour: "brown",
    cost: {},
    effect: { type: "produce", options: [["wood"]] },
  },
  {
    id: "lumber_yard_4p",
    name: "Lumber Yard",
    age: 1,
    minPlayers: 4,
    colour: "brown",
    cost: {},
    effect: { type: "produce", options: [["wood"]] },
  },
  {
    id: "stone_pit_3p",
    name: "Stone Pit",
    age: 1,
    minPlayers: 3,
    colour: "brown",
    cost: {},
    effect: { type: "produce", options: [["stone"]] },
  },
  {
    id: "stone_pit_5p",
    name: "Stone Pit",
    age: 1,
    minPlayers: 5,
    colour: "brown",
    cost: {},
    effect: { type: "produce", options: [["stone"]] },
  },
  {
    id: "clay_pool_3p",
    name: "Clay Pool",
    age: 1,
    minPlayers: 3,
    colour: "brown",
    cost: {},
    effect: { type: "produce", options: [["clay"]] },
  },
  {
    id: "clay_pool_5p",
    name: "Clay Pool",
    age: 1,
    minPlayers: 5,
    colour: "brown",
    cost: {},
    effect: { type: "produce", options: [["clay"]] },
  },
  {
    id: "ore_vein_3p",
    name: "Ore Vein",
    age: 1,
    minPlayers: 3,
    colour: "brown",
    cost: {},
    effect: { type: "produce", options: [["ore"]] },
  },
  {
    id: "ore_vein_4p",
    name: "Ore Vein",
    age: 1,
    minPlayers: 4,
    colour: "brown",
    cost: {},
    effect: { type: "produce", options: [["ore"]] },
  },
  {
    id: "tree_farm_6p",
    name: "Tree Farm",
    age: 1,
    minPlayers: 6,
    colour: "brown",
    cost: { coins: 1 },
    effect: { type: "produce", options: [["wood"], ["clay"]] },
  },
  {
    id: "excavation_4p",
    name: "Excavation",
    age: 1,
    minPlayers: 4,
    colour: "brown",
    cost: { coins: 1 },
    effect: { type: "produce", options: [["stone"], ["clay"]] },
  },
  {
    id: "clay_pit_3p",
    name: "Clay Pit",
    age: 1,
    minPlayers: 3,
    colour: "brown",
    cost: { coins: 1 },
    effect: { type: "produce", options: [["clay"], ["ore"]] },
  },
  {
    id: "timber_yard_3p",
    name: "Timber Yard",
    age: 1,
    minPlayers: 3,
    colour: "brown",
    cost: { coins: 1 },
    effect: { type: "produce", options: [["stone"], ["wood"]] },
  },
  {
    id: "forest_cave_5p",
    name: "Forest Cave",
    age: 1,
    minPlayers: 5,
    colour: "brown",
    cost: { coins: 1 },
    effect: { type: "produce", options: [["wood"], ["ore"]] },
  },
  {
    id: "mine_6p",
    name: "Mine",
    age: 1,
    minPlayers: 6,
    colour: "brown",
    cost: { coins: 1 },
    effect: { type: "produce", options: [["ore"], ["stone"]] },
  },

  // ─── AGE I ─── GREY (manufactured goods) ───
  {
    id: "loom_3p",
    name: "Loom",
    age: 1,
    minPlayers: 3,
    colour: "grey",
    cost: {},
    effect: { type: "produce", options: [["textile"]] },
  },
  {
    id: "loom_6p",
    name: "Loom",
    age: 1,
    minPlayers: 6,
    colour: "grey",
    cost: {},
    effect: { type: "produce", options: [["textile"]] },
  },
  {
    id: "glassworks_3p",
    name: "Glassworks",
    age: 1,
    minPlayers: 3,
    colour: "grey",
    cost: {},
    effect: { type: "produce", options: [["glass"]] },
  },
  {
    id: "glassworks_6p",
    name: "Glassworks",
    age: 1,
    minPlayers: 6,
    colour: "grey",
    cost: {},
    effect: { type: "produce", options: [["glass"]] },
  },
  {
    id: "press_3p",
    name: "Press",
    age: 1,
    minPlayers: 3,
    colour: "grey",
    cost: {},
    effect: { type: "produce", options: [["papyrus"]] },
  },
  {
    id: "press_6p",
    name: "Press",
    age: 1,
    minPlayers: 6,
    colour: "grey",
    cost: {},
    effect: { type: "produce", options: [["papyrus"]] },
  },

  // ─── AGE I ─── BLUE (civilian) ───
  {
    id: "pawnshop_4p",
    name: "Pawnshop",
    age: 1,
    minPlayers: 4,
    colour: "blue",
    cost: {},
    effect: { type: "points", amount: 3 },
  },
  {
    id: "pawnshop_7p",
    name: "Pawnshop",
    age: 1,
    minPlayers: 7,
    colour: "blue",
    cost: {},
    effect: { type: "points", amount: 3 },
  },
  {
    id: "baths_3p",
    name: "Baths",
    age: 1,
    minPlayers: 3,
    colour: "blue",
    cost: { resources: { stone: 1 } },
    chainTo: ["Aqueduct"],
    effect: { type: "points", amount: 3 },
  },
  {
    id: "baths_7p",
    name: "Baths",
    age: 1,
    minPlayers: 7,
    colour: "blue",
    cost: { resources: { stone: 1 } },
    chainTo: ["Aqueduct"],
    effect: { type: "points", amount: 3 },
  },
  {
    id: "altar_3p",
    name: "Altar",
    age: 1,
    minPlayers: 3,
    colour: "blue",
    cost: {},
    chainTo: ["Temple"],
    effect: { type: "points", amount: 2 },
  },
  {
    id: "altar_5p",
    name: "Altar",
    age: 1,
    minPlayers: 5,
    colour: "blue",
    cost: {},
    chainTo: ["Temple"],
    effect: { type: "points", amount: 2 },
  },
  {
    id: "theater_3p",
    name: "Theater",
    age: 1,
    minPlayers: 3,
    colour: "blue",
    cost: {},
    chainTo: ["Statue"],
    effect: { type: "points", amount: 2 },
  },
  {
    id: "theater_6p",
    name: "Theater",
    age: 1,
    minPlayers: 6,
    colour: "blue",
    cost: {},
    chainTo: ["Statue"],
    effect: { type: "points", amount: 2 },
  },

  // ─── AGE I ─── YELLOW (commercial) ───
  {
    id: "tavern_4p",
    name: "Tavern",
    age: 1,
    minPlayers: 4,
    colour: "yellow",
    cost: {},
    effect: { type: "coins", amount: 5 },
  },
  {
    id: "tavern_5p",
    name: "Tavern",
    age: 1,
    minPlayers: 5,
    colour: "yellow",
    cost: {},
    effect: { type: "coins", amount: 5 },
  },
  {
    id: "tavern_7p",
    name: "Tavern",
    age: 1,
    minPlayers: 7,
    colour: "yellow",
    cost: {},
    effect: { type: "coins", amount: 5 },
  },
  {
    id: "east_trading_post_3p",
    name: "East Trading Post",
    age: 1,
    minPlayers: 3,
    colour: "yellow",
    cost: {},
    chainTo: ["Forum"],
    effect: { type: "tradingPost", direction: "right", kind: "raw" },
  },
  {
    id: "east_trading_post_7p",
    name: "East Trading Post",
    age: 1,
    minPlayers: 7,
    colour: "yellow",
    cost: {},
    chainTo: ["Forum"],
    effect: { type: "tradingPost", direction: "right", kind: "raw" },
  },
  {
    id: "west_trading_post_3p",
    name: "West Trading Post",
    age: 1,
    minPlayers: 3,
    colour: "yellow",
    cost: {},
    chainTo: ["Forum"],
    effect: { type: "tradingPost", direction: "left", kind: "raw" },
  },
  {
    id: "west_trading_post_7p",
    name: "West Trading Post",
    age: 1,
    minPlayers: 7,
    colour: "yellow",
    cost: {},
    chainTo: ["Forum"],
    effect: { type: "tradingPost", direction: "left", kind: "raw" },
  },
  {
    id: "marketplace_3p",
    name: "Marketplace",
    age: 1,
    minPlayers: 3,
    colour: "yellow",
    cost: {},
    chainTo: ["Caravansery"],
    effect: { type: "tradingPost", direction: "both", kind: "manufactured" },
  },
  {
    id: "marketplace_6p",
    name: "Marketplace",
    age: 1,
    minPlayers: 6,
    colour: "yellow",
    cost: {},
    chainTo: ["Caravansery"],
    effect: { type: "tradingPost", direction: "both", kind: "manufactured" },
  },

  // ─── AGE I ─── RED (military) ───
  {
    id: "stockade_3p",
    name: "Stockade",
    age: 1,
    minPlayers: 3,
    colour: "red",
    cost: { resources: { wood: 1 } },
    effect: { type: "shields", amount: 1 },
  },
  {
    id: "stockade_7p",
    name: "Stockade",
    age: 1,
    minPlayers: 7,
    colour: "red",
    cost: { resources: { wood: 1 } },
    effect: { type: "shields", amount: 1 },
  },
  {
    id: "barracks_3p",
    name: "Barracks",
    age: 1,
    minPlayers: 3,
    colour: "red",
    cost: { resources: { ore: 1 } },
    effect: { type: "shields", amount: 1 },
  },
  {
    id: "barracks_5p",
    name: "Barracks",
    age: 1,
    minPlayers: 5,
    colour: "red",
    cost: { resources: { ore: 1 } },
    effect: { type: "shields", amount: 1 },
  },
  {
    id: "guard_tower_3p",
    name: "Guard Tower",
    age: 1,
    minPlayers: 3,
    colour: "red",
    cost: { resources: { clay: 1 } },
    effect: { type: "shields", amount: 1 },
  },
  {
    id: "guard_tower_4p",
    name: "Guard Tower",
    age: 1,
    minPlayers: 4,
    colour: "red",
    cost: { resources: { clay: 1 } },
    effect: { type: "shields", amount: 1 },
  },

  // ─── AGE I ─── GREEN (science) ───
  {
    id: "apothecary_3p",
    name: "Apothecary",
    age: 1,
    minPlayers: 3,
    colour: "green",
    cost: { resources: { textile: 1 } },
    chainTo: ["Stables", "Dispensary"],
    effect: { type: "science", symbol: "compass" },
  },
  {
    id: "apothecary_5p",
    name: "Apothecary",
    age: 1,
    minPlayers: 5,
    colour: "green",
    cost: { resources: { textile: 1 } },
    chainTo: ["Stables", "Dispensary"],
    effect: { type: "science", symbol: "compass" },
  },
  {
    id: "workshop_3p",
    name: "Workshop",
    age: 1,
    minPlayers: 3,
    colour: "green",
    cost: { resources: { glass: 1 } },
    chainTo: ["Archery Range", "Laboratory"],
    effect: { type: "science", symbol: "gear" },
  },
  {
    id: "workshop_7p",
    name: "Workshop",
    age: 1,
    minPlayers: 7,
    colour: "green",
    cost: { resources: { glass: 1 } },
    chainTo: ["Archery Range", "Laboratory"],
    effect: { type: "science", symbol: "gear" },
  },
  {
    id: "scriptorium_3p",
    name: "Scriptorium",
    age: 1,
    minPlayers: 3,
    colour: "green",
    cost: { resources: { papyrus: 1 } },
    chainTo: ["Courthouse", "Library"],
    effect: { type: "science", symbol: "tablet" },
  },
  {
    id: "scriptorium_4p",
    name: "Scriptorium",
    age: 1,
    minPlayers: 4,
    colour: "green",
    cost: { resources: { papyrus: 1 } },
    chainTo: ["Courthouse", "Library"],
    effect: { type: "science", symbol: "tablet" },
  },

  // ─── AGE II ─── BROWN ───
  {
    id: "sawmill_3p",
    name: "Sawmill",
    age: 2,
    minPlayers: 3,
    colour: "brown",
    cost: { coins: 1 },
    effect: { type: "produceAll", resources: { wood: 2 } },
  },
  {
    id: "sawmill_4p",
    name: "Sawmill",
    age: 2,
    minPlayers: 4,
    colour: "brown",
    cost: { coins: 1 },
    effect: { type: "produceAll", resources: { wood: 2 } },
  },
  {
    id: "quarry_3p",
    name: "Quarry",
    age: 2,
    minPlayers: 3,
    colour: "brown",
    cost: { coins: 1 },
    effect: { type: "produceAll", resources: { stone: 2 } },
  },
  {
    id: "quarry_4p",
    name: "Quarry",
    age: 2,
    minPlayers: 4,
    colour: "brown",
    cost: { coins: 1 },
    effect: { type: "produceAll", resources: { stone: 2 } },
  },
  {
    id: "brickyard_3p",
    name: "Brickyard",
    age: 2,
    minPlayers: 3,
    colour: "brown",
    cost: { coins: 1 },
    effect: { type: "produceAll", resources: { clay: 2 } },
  },
  {
    id: "brickyard_4p",
    name: "Brickyard",
    age: 2,
    minPlayers: 4,
    colour: "brown",
    cost: { coins: 1 },
    effect: { type: "produceAll", resources: { clay: 2 } },
  },
  {
    id: "foundry_3p",
    name: "Foundry",
    age: 2,
    minPlayers: 3,
    colour: "brown",
    cost: { coins: 1 },
    effect: { type: "produceAll", resources: { ore: 2 } },
  },
  {
    id: "foundry_4p",
    name: "Foundry",
    age: 2,
    minPlayers: 4,
    colour: "brown",
    cost: { coins: 1 },
    effect: { type: "produceAll", resources: { ore: 2 } },
  },

  // ─── AGE II ─── GREY ───
  {
    id: "loom_ii_3p",
    name: "Loom",
    age: 2,
    minPlayers: 3,
    colour: "grey",
    cost: {},
    effect: { type: "produce", options: [["textile"]] },
  },
  {
    id: "loom_ii_5p",
    name: "Loom",
    age: 2,
    minPlayers: 5,
    colour: "grey",
    cost: {},
    effect: { type: "produce", options: [["textile"]] },
  },
  {
    id: "glassworks_ii_3p",
    name: "Glassworks",
    age: 2,
    minPlayers: 3,
    colour: "grey",
    cost: {},
    effect: { type: "produce", options: [["glass"]] },
  },
  {
    id: "glassworks_ii_5p",
    name: "Glassworks",
    age: 2,
    minPlayers: 5,
    colour: "grey",
    cost: {},
    effect: { type: "produce", options: [["glass"]] },
  },
  {
    id: "press_ii_3p",
    name: "Press",
    age: 2,
    minPlayers: 3,
    colour: "grey",
    cost: {},
    effect: { type: "produce", options: [["papyrus"]] },
  },
  {
    id: "press_ii_5p",
    name: "Press",
    age: 2,
    minPlayers: 5,
    colour: "grey",
    cost: {},
    effect: { type: "produce", options: [["papyrus"]] },
  },

  // ─── AGE II ─── BLUE ───
  {
    id: "aqueduct_3p",
    name: "Aqueduct",
    age: 2,
    minPlayers: 3,
    colour: "blue",
    cost: { resources: { stone: 3 } },
    freeChainFrom: ["Baths"],
    effect: { type: "points", amount: 5 },
  },
  {
    id: "aqueduct_7p",
    name: "Aqueduct",
    age: 2,
    minPlayers: 7,
    colour: "blue",
    cost: { resources: { stone: 3 } },
    freeChainFrom: ["Baths"],
    effect: { type: "points", amount: 5 },
  },
  {
    id: "temple_3p",
    name: "Temple",
    age: 2,
    minPlayers: 3,
    colour: "blue",
    cost: { resources: { wood: 1, clay: 1, glass: 1 } },
    freeChainFrom: ["Altar"],
    chainTo: ["Pantheon"],
    effect: { type: "points", amount: 3 },
  },
  {
    id: "temple_6p",
    name: "Temple",
    age: 2,
    minPlayers: 6,
    colour: "blue",
    cost: { resources: { wood: 1, clay: 1, glass: 1 } },
    freeChainFrom: ["Altar"],
    chainTo: ["Pantheon"],
    effect: { type: "points", amount: 3 },
  },
  {
    id: "statue_3p",
    name: "Statue",
    age: 2,
    minPlayers: 3,
    colour: "blue",
    cost: { resources: { ore: 2, wood: 1 } },
    freeChainFrom: ["Theater"],
    chainTo: ["Gardens"],
    effect: { type: "points", amount: 4 },
  },
  {
    id: "statue_7p",
    name: "Statue",
    age: 2,
    minPlayers: 7,
    colour: "blue",
    cost: { resources: { ore: 2, wood: 1 } },
    freeChainFrom: ["Theater"],
    chainTo: ["Gardens"],
    effect: { type: "points", amount: 4 },
  },
  {
    id: "courthouse_3p",
    name: "Courthouse",
    age: 2,
    minPlayers: 3,
    colour: "blue",
    cost: { resources: { clay: 2, textile: 1 } },
    freeChainFrom: ["Scriptorium"],
    effect: { type: "points", amount: 4 },
  },
  {
    id: "courthouse_5p",
    name: "Courthouse",
    age: 2,
    minPlayers: 5,
    colour: "blue",
    cost: { resources: { clay: 2, textile: 1 } },
    freeChainFrom: ["Scriptorium"],
    effect: { type: "points", amount: 4 },
  },

  // ─── AGE II ─── YELLOW ───
  {
    id: "forum_3p",
    name: "Forum",
    age: 2,
    minPlayers: 3,
    colour: "yellow",
    cost: { resources: { clay: 2 } },
    freeChainFrom: ["East Trading Post", "West Trading Post"],
    chainTo: ["Haven"],
    effect: { type: "produce", options: [["glass"], ["textile"], ["papyrus"]] },
  },
  {
    id: "forum_6p",
    name: "Forum",
    age: 2,
    minPlayers: 6,
    colour: "yellow",
    cost: { resources: { clay: 2 } },
    freeChainFrom: ["East Trading Post", "West Trading Post"],
    chainTo: ["Haven"],
    effect: { type: "produce", options: [["glass"], ["textile"], ["papyrus"]] },
  },
  {
    id: "forum_7p",
    name: "Forum",
    age: 2,
    minPlayers: 7,
    colour: "yellow",
    cost: { resources: { clay: 2 } },
    freeChainFrom: ["East Trading Post", "West Trading Post"],
    chainTo: ["Haven"],
    effect: { type: "produce", options: [["glass"], ["textile"], ["papyrus"]] },
  },
  {
    id: "caravansery_3p",
    name: "Caravansery",
    age: 2,
    minPlayers: 3,
    colour: "yellow",
    cost: { resources: { wood: 2 } },
    freeChainFrom: ["Marketplace"],
    chainTo: ["Lighthouse"],
    effect: {
      type: "produce",
      options: [["wood"], ["stone"], ["ore"], ["clay"]],
    },
  },
  {
    id: "caravansery_5p",
    name: "Caravansery",
    age: 2,
    minPlayers: 5,
    colour: "yellow",
    cost: { resources: { wood: 2 } },
    freeChainFrom: ["Marketplace"],
    chainTo: ["Lighthouse"],
    effect: {
      type: "produce",
      options: [["wood"], ["stone"], ["ore"], ["clay"]],
    },
  },
  {
    id: "caravansery_6p",
    name: "Caravansery",
    age: 2,
    minPlayers: 6,
    colour: "yellow",
    cost: { resources: { wood: 2 } },
    freeChainFrom: ["Marketplace"],
    chainTo: ["Lighthouse"],
    effect: {
      type: "produce",
      options: [["wood"], ["stone"], ["ore"], ["clay"]],
    },
  },
  {
    id: "vineyard_3p",
    name: "Vineyard",
    age: 2,
    minPlayers: 3,
    colour: "yellow",
    cost: {},
    effect: { type: "coinsFromCards", colour: "brown", self: 1, neighbors: 1 },
  },
  {
    id: "vineyard_6p",
    name: "Vineyard",
    age: 2,
    minPlayers: 6,
    colour: "yellow",
    cost: {},
    effect: { type: "coinsFromCards", colour: "brown", self: 1, neighbors: 1 },
  },
  {
    id: "bazar_4p",
    name: "Bazar",
    age: 2,
    minPlayers: 4,
    colour: "yellow",
    cost: {},
    effect: { type: "coinsFromCards", colour: "grey", self: 2, neighbors: 2 },
  },
  {
    id: "bazar_7p",
    name: "Bazar",
    age: 2,
    minPlayers: 7,
    colour: "yellow",
    cost: {},
    effect: { type: "coinsFromCards", colour: "grey", self: 2, neighbors: 2 },
  },

  // ─── AGE II ─── RED ───
  {
    id: "walls_3p",
    name: "Walls",
    age: 2,
    minPlayers: 3,
    colour: "red",
    cost: { resources: { stone: 3 } },
    chainTo: ["Fortifications"],
    effect: { type: "shields", amount: 2 },
  },
  {
    id: "walls_7p",
    name: "Walls",
    age: 2,
    minPlayers: 7,
    colour: "red",
    cost: { resources: { stone: 3 } },
    chainTo: ["Fortifications"],
    effect: { type: "shields", amount: 2 },
  },
  {
    id: "training_ground_4p",
    name: "Training Ground",
    age: 2,
    minPlayers: 4,
    colour: "red",
    cost: { resources: { ore: 2, wood: 1 } },
    chainTo: ["Circus"],
    effect: { type: "shields", amount: 2 },
  },
  {
    id: "training_ground_6p",
    name: "Training Ground",
    age: 2,
    minPlayers: 6,
    colour: "red",
    cost: { resources: { ore: 2, wood: 1 } },
    chainTo: ["Circus"],
    effect: { type: "shields", amount: 2 },
  },
  {
    id: "training_ground_7p",
    name: "Training Ground",
    age: 2,
    minPlayers: 7,
    colour: "red",
    cost: { resources: { ore: 2, wood: 1 } },
    chainTo: ["Circus"],
    effect: { type: "shields", amount: 2 },
  },
  {
    id: "stables_3p",
    name: "Stables",
    age: 2,
    minPlayers: 3,
    colour: "red",
    cost: { resources: { clay: 1, wood: 1, ore: 1 } },
    freeChainFrom: ["Apothecary"],
    effect: { type: "shields", amount: 2 },
  },
  {
    id: "stables_5p",
    name: "Stables",
    age: 2,
    minPlayers: 5,
    colour: "red",
    cost: { resources: { clay: 1, wood: 1, ore: 1 } },
    freeChainFrom: ["Apothecary"],
    effect: { type: "shields", amount: 2 },
  },
  {
    id: "archery_range_3p",
    name: "Archery Range",
    age: 2,
    minPlayers: 3,
    colour: "red",
    cost: { resources: { wood: 2, ore: 1 } },
    freeChainFrom: ["Workshop"],
    effect: { type: "shields", amount: 2 },
  },
  {
    id: "archery_range_6p",
    name: "Archery Range",
    age: 2,
    minPlayers: 6,
    colour: "red",
    cost: { resources: { wood: 2, ore: 1 } },
    freeChainFrom: ["Workshop"],
    effect: { type: "shields", amount: 2 },
  },

  // ─── AGE II ─── GREEN ───
  {
    id: "dispensary_3p",
    name: "Dispensary",
    age: 2,
    minPlayers: 3,
    colour: "green",
    cost: { resources: { ore: 2, glass: 1 } },
    freeChainFrom: ["Apothecary"],
    chainTo: ["Arena", "Lodge"],
    effect: { type: "science", symbol: "compass" },
  },
  {
    id: "dispensary_4p",
    name: "Dispensary",
    age: 2,
    minPlayers: 4,
    colour: "green",
    cost: { resources: { ore: 2, glass: 1 } },
    freeChainFrom: ["Apothecary"],
    chainTo: ["Arena", "Lodge"],
    effect: { type: "science", symbol: "compass" },
  },
  {
    id: "laboratory_3p",
    name: "Laboratory",
    age: 2,
    minPlayers: 3,
    colour: "green",
    cost: { resources: { clay: 2, papyrus: 1 } },
    freeChainFrom: ["Workshop"],
    chainTo: ["Siege Workshop", "Observatory"],
    effect: { type: "science", symbol: "gear" },
  },
  {
    id: "laboratory_5p",
    name: "Laboratory",
    age: 2,
    minPlayers: 5,
    colour: "green",
    cost: { resources: { clay: 2, papyrus: 1 } },
    freeChainFrom: ["Workshop"],
    chainTo: ["Siege Workshop", "Observatory"],
    effect: { type: "science", symbol: "gear" },
  },
  {
    id: "library_3p",
    name: "Library",
    age: 2,
    minPlayers: 3,
    colour: "green",
    cost: { resources: { stone: 2, textile: 1 } },
    freeChainFrom: ["Scriptorium"],
    chainTo: ["Senate", "University"],
    effect: { type: "science", symbol: "tablet" },
  },
  {
    id: "library_6p",
    name: "Library",
    age: 2,
    minPlayers: 6,
    colour: "green",
    cost: { resources: { stone: 2, textile: 1 } },
    freeChainFrom: ["Scriptorium"],
    chainTo: ["Senate", "University"],
    effect: { type: "science", symbol: "tablet" },
  },
  {
    id: "school_3p",
    name: "School",
    age: 2,
    minPlayers: 3,
    colour: "green",
    cost: { resources: { wood: 1, papyrus: 1 } },
    chainTo: ["Academy", "Study"],
    effect: { type: "science", symbol: "tablet" },
  },
  {
    id: "school_7p",
    name: "School",
    age: 2,
    minPlayers: 7,
    colour: "green",
    cost: { resources: { wood: 1, papyrus: 1 } },
    chainTo: ["Academy", "Study"],
    effect: { type: "science", symbol: "tablet" },
  },

  // ─── AGE III ─── BLUE ───
  {
    id: "pantheon_3p",
    name: "Pantheon",
    age: 3,
    minPlayers: 3,
    colour: "blue",
    cost: { resources: { clay: 2, ore: 1, glass: 1, papyrus: 1, textile: 1 } },
    freeChainFrom: ["Temple"],
    effect: { type: "points", amount: 7 },
  },
  {
    id: "pantheon_6p",
    name: "Pantheon",
    age: 3,
    minPlayers: 6,
    colour: "blue",
    cost: { resources: { clay: 2, ore: 1, glass: 1, papyrus: 1, textile: 1 } },
    freeChainFrom: ["Temple"],
    effect: { type: "points", amount: 7 },
  },
  {
    id: "gardens_3p",
    name: "Gardens",
    age: 3,
    minPlayers: 3,
    colour: "blue",
    cost: { resources: { clay: 2, wood: 1 } },
    freeChainFrom: ["Statue"],
    effect: { type: "points", amount: 5 },
  },
  {
    id: "gardens_4p",
    name: "Gardens",
    age: 3,
    minPlayers: 4,
    colour: "blue",
    cost: { resources: { clay: 2, wood: 1 } },
    freeChainFrom: ["Statue"],
    effect: { type: "points", amount: 5 },
  },
  {
    id: "town_hall_3p",
    name: "Town Hall",
    age: 3,
    minPlayers: 3,
    colour: "blue",
    cost: { resources: { stone: 2, ore: 1, glass: 1 } },
    effect: { type: "points", amount: 6 },
  },
  {
    id: "town_hall_5p",
    name: "Town Hall",
    age: 3,
    minPlayers: 5,
    colour: "blue",
    cost: { resources: { stone: 2, ore: 1, glass: 1 } },
    effect: { type: "points", amount: 6 },
  },
  {
    id: "town_hall_6p",
    name: "Town Hall",
    age: 3,
    minPlayers: 6,
    colour: "blue",
    cost: { resources: { stone: 2, ore: 1, glass: 1 } },
    effect: { type: "points", amount: 6 },
  },
  {
    id: "palace_3p",
    name: "Palace",
    age: 3,
    minPlayers: 3,
    colour: "blue",
    cost: {
      resources: {
        stone: 1,
        ore: 1,
        wood: 1,
        clay: 1,
        glass: 1,
        papyrus: 1,
        textile: 1,
      },
    },
    effect: { type: "points", amount: 8 },
  },
  {
    id: "palace_7p",
    name: "Palace",
    age: 3,
    minPlayers: 7,
    colour: "blue",
    cost: {
      resources: {
        stone: 1,
        ore: 1,
        wood: 1,
        clay: 1,
        glass: 1,
        papyrus: 1,
        textile: 1,
      },
    },
    effect: { type: "points", amount: 8 },
  },
  {
    id: "senate_3p",
    name: "Senate",
    age: 3,
    minPlayers: 3,
    colour: "blue",
    cost: { resources: { wood: 2, stone: 1, ore: 1 } },
    freeChainFrom: ["Library"],
    effect: { type: "points", amount: 6 },
  },
  {
    id: "senate_5p",
    name: "Senate",
    age: 3,
    minPlayers: 5,
    colour: "blue",
    cost: { resources: { wood: 2, stone: 1, ore: 1 } },
    freeChainFrom: ["Library"],
    effect: { type: "points", amount: 6 },
  },

  // ─── AGE III ─── YELLOW ───
  {
    id: "haven_3p",
    name: "Haven",
    age: 3,
    minPlayers: 3,
    colour: "yellow",
    cost: { resources: { wood: 1, ore: 1, textile: 1 } },
    freeChainFrom: ["Forum"],
    effect: {
      type: "endGamePoints",
      colour: "brown",
      self: 1,
      neighbors: 0,
    },
  },
  {
    id: "haven_4p",
    name: "Haven",
    age: 3,
    minPlayers: 4,
    colour: "yellow",
    cost: { resources: { wood: 1, ore: 1, textile: 1 } },
    freeChainFrom: ["Forum"],
    effect: {
      type: "endGamePoints",
      colour: "brown",
      self: 1,
      neighbors: 0,
    },
  },
  {
    id: "lighthouse_3p",
    name: "Lighthouse",
    age: 3,
    minPlayers: 3,
    colour: "yellow",
    cost: { resources: { stone: 1, glass: 1 } },
    freeChainFrom: ["Caravansery"],
    effect: {
      type: "endGamePoints",
      colour: "yellow",
      self: 1,
      neighbors: 0,
    },
  },
  {
    id: "lighthouse_6p",
    name: "Lighthouse",
    age: 3,
    minPlayers: 6,
    colour: "yellow",
    cost: { resources: { stone: 1, glass: 1 } },
    freeChainFrom: ["Caravansery"],
    effect: {
      type: "endGamePoints",
      colour: "yellow",
      self: 1,
      neighbors: 0,
    },
  },
  {
    id: "chamber_of_commerce_4p",
    name: "Chamber of Commerce",
    age: 3,
    minPlayers: 4,
    colour: "yellow",
    cost: { resources: { clay: 2, papyrus: 1 } },
    effect: {
      type: "endGamePoints",
      colour: "grey",
      self: 2,
      neighbors: 0,
    },
  },
  {
    id: "chamber_of_commerce_6p",
    name: "Chamber of Commerce",
    age: 3,
    minPlayers: 6,
    colour: "yellow",
    cost: { resources: { clay: 2, papyrus: 1 } },
    effect: {
      type: "endGamePoints",
      colour: "grey",
      self: 2,
      neighbors: 0,
    },
  },
  {
    id: "arena_3p",
    name: "Arena",
    age: 3,
    minPlayers: 3,
    colour: "yellow",
    cost: { resources: { stone: 2, ore: 1 } },
    freeChainFrom: ["Dispensary"],
    effect: {
      type: "endGamePoints",
      colour: "wonderStages",
      self: 1,
      neighbors: 0,
    },
  },
  {
    id: "arena_5p",
    name: "Arena",
    age: 3,
    minPlayers: 5,
    colour: "yellow",
    cost: { resources: { stone: 2, ore: 1 } },
    freeChainFrom: ["Dispensary"],
    effect: {
      type: "endGamePoints",
      colour: "wonderStages",
      self: 1,
      neighbors: 0,
    },
  },
  {
    id: "arena_7p",
    name: "Arena",
    age: 3,
    minPlayers: 7,
    colour: "yellow",
    cost: { resources: { stone: 2, ore: 1 } },
    freeChainFrom: ["Dispensary"],
    effect: {
      type: "endGamePoints",
      colour: "wonderStages",
      self: 1,
      neighbors: 0,
    },
  },

  // ─── AGE III ─── RED ───
  {
    id: "fortifications_3p",
    name: "Fortifications",
    age: 3,
    minPlayers: 3,
    colour: "red",
    cost: { resources: { ore: 3, stone: 1 } },
    freeChainFrom: ["Walls"],
    effect: { type: "shields", amount: 3 },
  },
  {
    id: "fortifications_7p",
    name: "Fortifications",
    age: 3,
    minPlayers: 7,
    colour: "red",
    cost: { resources: { ore: 3, stone: 1 } },
    freeChainFrom: ["Walls"],
    effect: { type: "shields", amount: 3 },
  },
  {
    id: "circus_4p",
    name: "Circus",
    age: 3,
    minPlayers: 4,
    colour: "red",
    cost: { resources: { stone: 3, ore: 1 } },
    freeChainFrom: ["Training Ground"],
    effect: { type: "shields", amount: 3 },
  },
  {
    id: "circus_5p",
    name: "Circus",
    age: 3,
    minPlayers: 5,
    colour: "red",
    cost: { resources: { stone: 3, ore: 1 } },
    freeChainFrom: ["Training Ground"],
    effect: { type: "shields", amount: 3 },
  },
  {
    id: "circus_6p",
    name: "Circus",
    age: 3,
    minPlayers: 6,
    colour: "red",
    cost: { resources: { stone: 3, ore: 1 } },
    freeChainFrom: ["Training Ground"],
    effect: { type: "shields", amount: 3 },
  },
  {
    id: "arsenal_3p",
    name: "Arsenal",
    age: 3,
    minPlayers: 3,
    colour: "red",
    cost: { resources: { wood: 2, ore: 1, textile: 1 } },
    effect: { type: "shields", amount: 3 },
  },
  {
    id: "arsenal_4p",
    name: "Arsenal",
    age: 3,
    minPlayers: 4,
    colour: "red",
    cost: { resources: { wood: 2, ore: 1, textile: 1 } },
    effect: { type: "shields", amount: 3 },
  },
  {
    id: "arsenal_7p",
    name: "Arsenal",
    age: 3,
    minPlayers: 7,
    colour: "red",
    cost: { resources: { wood: 2, ore: 1, textile: 1 } },
    effect: { type: "shields", amount: 3 },
  },
  {
    id: "siege_workshop_3p",
    name: "Siege Workshop",
    age: 3,
    minPlayers: 3,
    colour: "red",
    cost: { resources: { clay: 3, wood: 1 } },
    freeChainFrom: ["Laboratory"],
    effect: { type: "shields", amount: 3 },
  },
  {
    id: "siege_workshop_5p",
    name: "Siege Workshop",
    age: 3,
    minPlayers: 5,
    colour: "red",
    cost: { resources: { clay: 3, wood: 1 } },
    freeChainFrom: ["Laboratory"],
    effect: { type: "shields", amount: 3 },
  },

  // ─── AGE III ─── GREEN ───
  {
    id: "lodge_3p",
    name: "Lodge",
    age: 3,
    minPlayers: 3,
    colour: "green",
    cost: { resources: { clay: 2, papyrus: 1, textile: 1 } },
    freeChainFrom: ["Dispensary"],
    effect: { type: "science", symbol: "compass" },
  },
  {
    id: "lodge_6p",
    name: "Lodge",
    age: 3,
    minPlayers: 6,
    colour: "green",
    cost: { resources: { clay: 2, papyrus: 1, textile: 1 } },
    freeChainFrom: ["Dispensary"],
    effect: { type: "science", symbol: "compass" },
  },
  {
    id: "observatory_3p",
    name: "Observatory",
    age: 3,
    minPlayers: 3,
    colour: "green",
    cost: { resources: { ore: 2, glass: 1, textile: 1 } },
    freeChainFrom: ["Laboratory"],
    effect: { type: "science", symbol: "gear" },
  },
  {
    id: "observatory_7p",
    name: "Observatory",
    age: 3,
    minPlayers: 7,
    colour: "green",
    cost: { resources: { ore: 2, glass: 1, textile: 1 } },
    freeChainFrom: ["Laboratory"],
    effect: { type: "science", symbol: "gear" },
  },
  {
    id: "university_3p",
    name: "University",
    age: 3,
    minPlayers: 3,
    colour: "green",
    cost: { resources: { wood: 2, papyrus: 1, glass: 1 } },
    freeChainFrom: ["Library"],
    effect: { type: "science", symbol: "tablet" },
  },
  {
    id: "university_4p",
    name: "University",
    age: 3,
    minPlayers: 4,
    colour: "green",
    cost: { resources: { wood: 2, papyrus: 1, glass: 1 } },
    freeChainFrom: ["Library"],
    effect: { type: "science", symbol: "tablet" },
  },
  {
    id: "academy_3p",
    name: "Academy",
    age: 3,
    minPlayers: 3,
    colour: "green",
    cost: { resources: { stone: 3, glass: 1 } },
    freeChainFrom: ["School"],
    effect: { type: "science", symbol: "compass" },
  },
  {
    id: "academy_7p",
    name: "Academy",
    age: 3,
    minPlayers: 7,
    colour: "green",
    cost: { resources: { stone: 3, glass: 1 } },
    freeChainFrom: ["School"],
    effect: { type: "science", symbol: "compass" },
  },
  {
    id: "study_3p",
    name: "Study",
    age: 3,
    minPlayers: 3,
    colour: "green",
    cost: { resources: { wood: 1, papyrus: 1, textile: 1 } },
    freeChainFrom: ["School"],
    effect: { type: "science", symbol: "gear" },
  },
  {
    id: "study_5p",
    name: "Study",
    age: 3,
    minPlayers: 5,
    colour: "green",
    cost: { resources: { wood: 1, papyrus: 1, textile: 1 } },
    freeChainFrom: ["School"],
    effect: { type: "science", symbol: "gear" },
  },

  // ─── AGE III ─── PURPLE (guilds) ───
  {
    id: "workers_guild",
    name: "Workers Guild",
    age: 3,
    minPlayers: 3,
    colour: "purple",
    cost: { resources: { ore: 2, clay: 1, stone: 1, wood: 1 } },
    effect: {
      type: "guild",
      scoring: { kind: "countNeighbourCards", colour: "brown", perCard: 1 },
    },
  },
  {
    id: "craftsmens_guild",
    name: "Craftsmens Guild",
    age: 3,
    minPlayers: 3,
    colour: "purple",
    cost: { resources: { ore: 2, stone: 2 } },
    effect: {
      type: "guild",
      scoring: { kind: "countNeighbourCards", colour: "grey", perCard: 2 },
    },
  },
  {
    id: "traders_guild",
    name: "Traders Guild",
    age: 3,
    minPlayers: 3,
    colour: "purple",
    cost: { resources: { glass: 1, textile: 1, papyrus: 1 } },
    effect: {
      type: "guild",
      scoring: { kind: "countNeighbourCards", colour: "yellow", perCard: 1 },
    },
  },
  {
    id: "philosophers_guild",
    name: "Philosophers Guild",
    age: 3,
    minPlayers: 3,
    colour: "purple",
    cost: { resources: { clay: 3, papyrus: 1, textile: 1 } },
    effect: {
      type: "guild",
      scoring: { kind: "countNeighbourCards", colour: "green", perCard: 1 },
    },
  },
  {
    id: "spies_guild",
    name: "Spies Guild",
    age: 3,
    minPlayers: 3,
    colour: "purple",
    cost: { resources: { clay: 3, glass: 1 } },
    effect: {
      type: "guild",
      scoring: { kind: "countNeighbourCards", colour: "red", perCard: 1 },
    },
  },
  {
    id: "magistrates_guild",
    name: "Magistrates Guild",
    age: 3,
    minPlayers: 3,
    colour: "purple",
    cost: { resources: { wood: 3, stone: 1, textile: 1 } },
    effect: {
      type: "guild",
      scoring: { kind: "countNeighbourCards", colour: "blue", perCard: 1 },
    },
  },
  {
    id: "shipowners_guild",
    name: "Shipowners Guild",
    age: 3,
    minPlayers: 3,
    colour: "purple",
    cost: { resources: { wood: 3, glass: 1, papyrus: 1 } },
    effect: {
      type: "guild",
      scoring: {
        kind: "countOwnCards",
        colours: ["brown", "grey", "purple"],
        perCard: 1,
      },
    },
  },
  {
    id: "strategists_guild",
    name: "Strategists Guild",
    age: 3,
    minPlayers: 3,
    colour: "purple",
    cost: { resources: { ore: 2, stone: 1, textile: 1 } },
    effect: {
      type: "guild",
      scoring: { kind: "countNeighbourCards", colour: "red", perCard: 1 },
    },
  },
  {
    id: "scientists_guild",
    name: "Scientists Guild",
    age: 3,
    minPlayers: 3,
    colour: "purple",
    cost: { resources: { wood: 2, ore: 2, papyrus: 1 } },
    effect: { type: "guild", scoring: { kind: "scienceWild" } },
  },
  {
    id: "builders_guild",
    name: "Builders Guild",
    age: 3,
    minPlayers: 3,
    colour: "purple",
    cost: { resources: { stone: 2, clay: 2, glass: 1 } },
    effect: {
      type: "guild",
      scoring: { kind: "countNeighbourWonderStages", perStage: 1 },
    },
  },
] as const;

const cardMap = new Map<string, CardDef>();
for (const c of ALL_CARDS) {
  cardMap.set(c.id, c);
}

export function getCardById(id: string): CardDef {
  const card = cardMap.get(id);
  if (!card) throw new Error(`Unknown card id: ${id}`);
  return card;
}

export function getCardsForAge(age: 1 | 2 | 3, playerCount: number): CardDef[] {
  return ALL_CARDS.filter((c) => c.age === age && c.minPlayers <= playerCount);
}
